-
  hosts: all
  remote_user: rabrice
  tasks:
    - name: Appendd lines to a file
      lineinfile: 
        dest: /tmp/iplist.txt
        insertafter: EOF
        line: "{{group_names}} {{inventory_hostname}} {{ ansible_distribution }} {{ ansible_distribution_version }}"
        state: present
      delegate_to: 192.168.3.206
      when: (ansible_facts['distribution'] == Dist and ansible_facts['distribution_major_version'] == Vers)
